# Generated by Django 6.1 on 2026-08-24 10:15

import django.db.models.deletion
from django.db import migrations, models


def seed_hotels(apps, schema_editor):
    Hotel = apps.get_model('travel', 'Hotel')
    Room = apps.get_model('travel', 'Room')

    paradise = Hotel.objects.create(
        name='Paradise Vista Resort & Spa',
        slug='paradise-vista',
        location='Maldives, Indian Ocean',
        image='images/dest-maldives.jpg',
        rating=4.8,
        price_per_person=1376,
        board_basis='All Inclusive',
        facilities=['Beachfront', 'Infinity Pool', 'Luxury Spa', 'Live Entertainment', 'Free High-Speed WiFi', '24/7 Room Service'],
    )
    sapphire = Hotel.objects.create(
        name='The Sapphire Oasis Resort',
        slug='sapphire-oasis',
        location='Paphos, Cyprus',
        image='images/dest-santorini.jpg',
        rating=4.8,
        price_per_person=849,
        board_basis='All Inclusive',
        facilities=['Free WiFi'],
    )
    windmill = Hotel.objects.create(
        name='Windmill Bay Boutique Hotel',
        slug='windmill-bay',
        location='Rhodes, Greece',
        image='images/dest-tenerife.jpg',
        rating=4.9,
        price_per_person=620,
        board_basis='Half Board',
        facilities=[],
    )
    Room.objects.bulk_create([
        Room(hotel=paradise, name='Standard Twin Room with Balcony', image='images/hotel-room.jpg', board_basis='Half Board', price_per_person=729, features=['Sleeps up to 2', 'Sea view guaranteed', 'Air conditioning & free Wi-Fi']),
        Room(hotel=paradise, name='Swim-up Double Room with Terrace', image='images/hotel-pool.jpg', board_basis='All Inclusive', price_per_person=989, features=['Private pool access', 'Complimentary welcome drink', 'Premium minibar included']),
    ])


def unseed_hotels(apps, schema_editor):
    apps.get_model('travel', 'Hotel').objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=160)),
                ('image', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('board_basis', models.CharField(max_length=80)),
                ('facilities', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('image', models.CharField(max_length=255)),
                ('board_basis', models.CharField(max_length=80)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('features', models.JSONField(default=list)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='travel.hotel')),
            ],
        ),
        migrations.RunPython(seed_hotels, unseed_hotels),
    ]
