# Generated by Django 6.1 on 2026-08-24 13:02

import django.db.models.deletion
from django.db import migrations, models


def seed_availability(apps, schema_editor):
    Availability = apps.get_model('travel', 'Availability')
    Room = apps.get_model('travel', 'Room')
    for room in Room.objects.all():
        Availability.objects.create(
            room=room,
            check_in='2026-07-15',
            check_out='2026-07-22',
            rooms_available=5,
        )


def remove_availability(apps, schema_editor):
    apps.get_model('travel', 'Availability').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_booking_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('rooms_available', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='travel.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'check_in', 'check_out'), name='unique_room_availability_period')],
            },
        ),
        migrations.RunPython(seed_availability, remove_availability),
    ]
