# Generated by Django 6.1 on 2026-08-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_booking_guests_room_max_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
