# Generated by Django 6.1 on 2026-08-26 14:44

import django.db.models.deletion
import travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_hotel_room_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='destinations/')),
            ],
            bases=(travel.models.PhotoMixin, models.Model),
        ),
        migrations.AddField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='travel.destination'),
        ),
    ]
