# Generated by Django 6.1 on 2026-08-26 14:45

from django.db import migrations

from django.utils.text import slugify

def create_destinations(apps, schema_editor):
    Hotel = apps.get_model('travel', 'Hotel')
    Destination = apps.get_model('travel', 'Destination')
    
    for hotel in Hotel.objects.all():
        if hotel.location:
            dest, created = Destination.objects.get_or_create(
                name=hotel.location,
                defaults={'slug': slugify(hotel.location)[:50]}
            )
            hotel.destination = dest
            hotel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_destination_hotel_destination'),
    ]

    operations = [
        migrations.RunPython(create_destinations),
    ]
