# Generated by Django 6.1 on 2026-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_migrate_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
    ]
