# Generated by Django 6.1 on 2026-08-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_hotel_owner_alter_hotel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/')),
                ('category', models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('amenities', 'Amenities'), ('other', 'Other')], default='other', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='travel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('category', models.CharField(choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('view', 'View'), ('other', 'Other')], default='other', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='travel.room')),
            ],
        ),
    ]
