# Generated by Django 6.1 on 2026-08-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_hotelimage_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='distance_to_center',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Distance to center in km', max_digits=5),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_rating',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='hotel',
            name='payment_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='property_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Guesthouse', 'Guesthouse/bed and breakfast'), ('Apartment', 'Entire homes & apartments'), ('Flat', 'Apartment/Flat'), ('Resort', 'Resort'), ('Hostel', 'Hostel'), ('Homestay', 'Homestay'), ('House', 'Entire House'), ('HolidayPark', 'Holiday park/caravan park')], default='Hotel', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('Single', 'Single/twin'), ('Double', 'Double'), ('King', 'King'), ('Queen', 'Queen'), ('Bunk', 'Bunk bed')], default='Double', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='kids_stay_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='room_offers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
