# Generated by Django 6.1 on 2026-08-27 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_hotel_distance_to_center_hotel_location_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=160)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mode_of_transport', models.CharField(choices=[('Flight', 'Flight'), ('Coach', 'Coach'), ('Private Transfer', 'Private Transfer')], default='Flight', max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='travel.destination')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.transportroute'),
        ),
    ]
