# Generated by Django 6.1 on 2026-08-27 00:54

from django.db import migrations


def populate_transport_routes(apps, schema_editor):
    Destination = apps.get_model('travel', 'Destination')
    TransportRoute = apps.get_model('travel', 'TransportRoute')
    
    origins = ['Islamabad', 'Lahore', 'Karachi', 'Peshawar', 'Multan', 'Quetta']
    prices = {
        'Islamabad': 15000,
        'Lahore': 20000,
        'Karachi': 35000,
        'Peshawar': 18000,
        'Multan': 25000,
        'Quetta': 30000,
    }
    
    destinations = Destination.objects.all()
    for dest in destinations:
        for origin in origins:
            TransportRoute.objects.get_or_create(
                origin=origin,
                destination=dest,
                defaults={
                    'price_per_person': prices[origin],
                    'mode_of_transport': 'Flight'
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_transportroute_booking_transport_route'),
    ]

    operations = [
        migrations.RunPython(populate_transport_routes),
    ]
